### PR TITLE
Migrate to python3

### PR DESCRIPTION
**Pull request by hu-chia**

### CODE REVIEW

**Comment by snooze92** [comment]
If I try to run the workflow locally with your code, I get:
```
[20:31:06.019] ERROR: Epoch Converter[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Ealfred-epoch-converter%3E84A7FB97-8BB7-459D-BC8D-81F919E0B448)] Code 1: Traceback (most recent call last):
  File "epoch.py", line 8, in <module>
    from importlib import reload
ImportError: cannot import name reload
```

If I update the workflow to use `/usr/bin/python3` instead of `/usr/bin/python` which still points to Python 2 on my machine, I get:
```
[20:32:16.923] ERROR: Epoch Converter[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Ealfred-epoch-converter%3E84A7FB97-8BB7-459D-BC8D-81F919E0B448)] Code 1: Traceback (most recent call last):
  File "epoch.py", line 10, in <module>
    from workflow import Workflow, ICON_CLOCK, ICON_NOTE
  File "/Users/jlehuen/Code/alfred-epoch-converter/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/jlehuen/Code/alfred-epoch-converter/workflow/workflow.py", line 45, in <module>
    from util import (
ModuleNotFoundError: No module named 'util'
```

If I turn a few imports into relative as well, it seems to work again...

In the end, I had to make these additional changes:
```diff
diff --git a/info.plist b/info.plist
index f25adf9..bdf961b 100644
--- a/info.plist
+++ b/info.plist
@@ -49,6 +49,8 @@
 				<false/>
 				<key>alfredfiltersresultsmatchmode</key>
 				<integer>0</integer>
+				<key>argumenttreatemptyqueryasnil</key>
+				<false/>
 				<key>argumenttrimmode</key>
 				<integer>0</integer>
 				<key>argumenttype</key>
@@ -68,7 +70,7 @@
 				<key>runningsubtext</key>
 				<string>Converting timestamp...</string>
 				<key>script</key>
-				<string>/usr/bin/python epoch.py "{query}"</string>
+				<string>/usr/bin/python3 epoch.py "{query}"</string>
 				<key>scriptargtype</key>
 				<integer>0</integer>
 				<key>scriptfile</key>
@@ -87,7 +89,7 @@
 			<key>uid</key>
 			<string>84A7FB97-8BB7-459D-BC8D-81F919E0B448</string>
 			<key>version</key>
-			<integer>2</integer>
+			<integer>3</integer>
 		</dict>
 		<dict>
 			<key>config</key>
@@ -96,6 +98,8 @@
 				<false/>
 				<key>clipboardtext</key>
 				<string>{query}</string>
+				<key>ignoredynamicplaceholders</key>
+				<false/>
 				<key>transient</key>
 				<false/>
 			</dict>
@@ -104,7 +108,7 @@
 			<key>uid</key>
 			<string>14ADF12A-3111-4EBB-BA77-E196F0FCC87D</string>
 			<key>version</key>
-			<integer>2</integer>
+			<integer>3</integer>
 		</dict>
 		<dict>
 			<key>config</key>
diff --git a/workflow/update.py b/workflow/update.py
index 44bd1a8..9856c5f 100644
--- a/workflow/update.py
+++ b/workflow/update.py
@@ -28,8 +28,8 @@ import tempfile
 import re
 import subprocess
 
-import workflow
-import web
+from . import workflow
+from . import web
 
 # __all__ = []
 
diff --git a/workflow/workflow.py b/workflow/workflow.py
index a7128b2..ec478a2 100644
--- a/workflow/workflow.py
+++ b/workflow/workflow.py
@@ -42,7 +42,7 @@ try:
 except ImportError:  # pragma: no cover
     import xml.etree.ElementTree as ET
 
-from util import (
+from .util import (
     # imported to maintain API
     atomic_writer,
     LockFile,
@@ -991,7 +991,7 @@ class Workflow(object):
     @property
     def alfred_version(self):
         """Alfred version as :class:`~workflow.update.Version` object."""
-        from update import Version
+        from .update import Version
         return Version(self.alfred_env.get('version'))
 
     @property
@@ -1172,7 +1172,7 @@ class Workflow(object):
                 version = self.info.get('version')
 
             if version:
-                from update import Version
+                from .update import Version
                 version = Version(version)
 
             self._version = version
```

I'd be curious to know how this worked for you locally, without these additional changes.

**Comment by hu-chia** [comment]
well, I changed my workflow config like this, but your change is the right way, could you just commit it or sent me a patch? 

image

**Comment by snooze92** [comment]
Alright, easiest is probably to merge this PR, and I'll follow-up with a separate commit.

Thank you! :)

**Comment by ebouchut** [comment]
👍🏻 Thanks @snooze92 and @guyeu for your time. 
Really helpful 👏🏻 .

**Pull request merged**
